In [1]:
import numpy as np

In [2]:
a = [i for i in range(10)]

In [3]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
b = np.array(a)

In [5]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
b.dtype

dtype('int32')

In [7]:
type(b)

numpy.ndarray

In [8]:
b = np.array(a, dtype = float)

In [9]:
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [10]:
b = np.array(a, dtype = str)

In [11]:
b

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U1')

In [12]:
b[0]

'0'

In [13]:
b[8]

'8'

In [14]:
b.ndim

1

In [15]:
b.shape

(10,)

In [16]:
b = np.array([[0,1,2,3,4,5,6,7,8,9],
              [10,11,12,13,14,15,16,17,18,19],
              [20,21,22,23,24,25,26,27,28,29]])

In [17]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [18]:
b[1][4]

14

In [19]:
b[2, 7]

27

In [20]:
b[0:,7:]

array([[ 7,  8,  9],
       [17, 18, 19],
       [27, 28, 29]])

In [21]:
c = b[0:,:5].copy()

In [22]:
c

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [23]:
c[2,3] = 555

In [24]:
c

array([[  0,   1,   2,   3,   4],
       [ 10,  11,  12,  13,  14],
       [ 20,  21,  22, 555,  24]])

In [25]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [26]:
mas = np.array([1,2,3,4], dtype=np.int64)

In [27]:
mas.dtype

dtype('int64')

In [28]:
mas.shape

(4,)

In [29]:
b.shape

(3, 10)

In [30]:
b.ndim

2

In [31]:
b.size

30

### Скалярное произведение векторов

In [32]:
a = np.array([1,2,3,4,5],dtype ="int32")
b = np.array([6,7,8,9,10],dtype ="int32")
sp = np.dot(a,b)
sp

130

### Скалярное умножение числа на вектор

In [33]:
a.dot(-5)

array([ -5, -10, -15, -20, -25])

## Операции с векторами

 Сложение

In [34]:
a = np.array([0, 1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10, 11])

In [35]:
c = a + b

In [36]:
c

array([ 6,  8, 10, 12, 14, 16])

In [37]:
c = np.add(a, b)

In [38]:
c

array([ 6,  8, 10, 12, 14, 16])

Вычитание

In [39]:
d = np.subtract(a,b)

In [40]:
d

array([-6, -6, -6, -6, -6, -6])

Умножение вектра на скаляр (число)

In [41]:
a = np.array([0, 1, 2, 3, 4, 5])

In [42]:
a.dot(-10)

array([  0, -10, -20, -30, -40, -50])

In [43]:
np.dot(a,-10)

array([  0, -10, -20, -30, -40, -50])

Скалярное умножение векторов

In [44]:
a = np.array([0, 1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10, 11])

In [45]:
sp = a @ b

In [46]:
sp

145

In [47]:
sp = np.dot(a,b)
sp

145

# Операции с матрицами

### Сложение, вычитание

In [48]:
A = np.array([[23, 34],
             [18, 12],
             [9, 5]])

In [49]:
B = np.array([[45, 22],
             [21, 3],
             [11, 99]])

In [50]:
C = np.add(A, B)
C

array([[ 68,  56],
       [ 39,  15],
       [ 20, 104]])

In [51]:
C = np.subtract(B, A)
C

array([[ 22, -12],
       [  3,  -9],
       [  2,  94]])

### Умножение матрицы на скаляр(число)

In [52]:
X = np.array([[12, 45],
             [22,15]])
X

array([[12, 45],
       [22, 15]])

In [53]:
Y = X * 2
Y

array([[24, 90],
       [44, 30]])

In [54]:
Y = np.dot(X, 4)
Y

array([[ 48, 180],
       [ 88,  60]])

### Умножение матрицы на матрицу
Кол-во столбцов 1 матрицы должно быть равное кол-ву строк 2 матрицы

In [55]:
A = np.array([[1, 2],
             [21, 12],
             [34, 7]])

B = np.array([[22, 32, 4],
             [7, 16, 11]])

In [56]:
Z = np.dot(A, B)
Z

array([[  36,   64,   26],
       [ 546,  864,  216],
       [ 797, 1200,  213]])

### Возведение матрицы в квадрат (матрица должна быть квадратная 2x2, 3x3 и тд.)

In [57]:
A = np.array([[1, 12, 21],
             [11, 3, 5],
             [8, 6, 9]])

In [58]:
A_square = np.dot(A, A)
A_square

array([[301, 174, 270],
       [ 84, 171, 291],
       [146, 168, 279]])

In [59]:
A_square = np.linalg.matrix_power(A, 2)
A_square

array([[301, 174, 270],
       [ 84, 171, 291],
       [146, 168, 279]])

### Создание и использование единичной матрицы.
Квадратная матрица с 1 на главной диагонали и остальными нулями. При умножении подходящей по размеру матрицы на единичную
матрица не меняется.

In [60]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])

In [62]:
np.dot(A, I)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [63]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [64]:
np.dot(I, A)

array([[1., 2., 3.],
       [4., 5., 6.]])

### Транспонирование матрицы

In [65]:
A = np.array([[1, 12],
             [11, 3],
             [8, 6]])

In [66]:
At = A.transpose()
At

array([[ 1, 11,  8],
       [12,  3,  6]])

In [67]:
At = A.T
At

array([[ 1, 11,  8],
       [12,  3,  6]])

Пример применения транспонирования матрицы (после транспонирования матрицы умножение возможно)

In [68]:
X = np.array([[1, 2],
             [3, 4],
             [5, 6]])

Y = np.array([[3, 4],
             [5, 6],
             [7, 8],
             [2, 9]])

In [69]:
Yt = Y.T
Yt

array([[3, 5, 7, 2],
       [4, 6, 8, 9]])

In [70]:
np.dot(X, Yt)

array([[11, 17, 23, 20],
       [25, 39, 53, 42],
       [39, 61, 83, 64]])

 ### Вычисление определителя и ранга матрицы 
    (Определитель можно найти только у квадратных матриц, ранг у всех)

In [74]:
A = np.array([[0, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

In [76]:
np.linalg.det(A)

2.9999999999999982

In [78]:
np.linalg.matrix_rank(A)

3

In [79]:
B = np.array([[0, 2, 3],
             [4, 5, 6]])

In [81]:
np.linalg.matrix_rank(B)

2

### Вычисление обратной матрицы

In [82]:
C = np.array([[1, 2, 3],
             [5, 6, 8],
             [2, 12, 21]])

In [84]:
C_inv = np.linalg.inv(C)
C_inv

array([[ -7.5 ,   1.5 ,   0.5 ],
       [ 22.25,  -3.75,  -1.75],
       [-12.  ,   2.  ,   1.  ]])

In [87]:
C_inv_2 = np.linalg.inv(C_inv)
C_inv_2

array([[ 1.,  2.,  3.],
       [ 5.,  6.,  8.],
       [ 2., 12., 21.]])

# Генерирование массивов

Генерация массива с нулями

In [89]:
A = np.zeros((3, 4))
A

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Генерация массива с единицами

In [91]:
B = np.ones((2,5))
B

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Генерация массива последовательности

In [94]:
C = np.arange(10)
C

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
C = np.arange(10, 0, -1)
C

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

linspace- правая граница будет включена, вместо шага указываем кол-во элементов.

In [104]:
np.linspace(0, 9.9, 100)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

Logspace - не сами числа, а степени числа 10

In [108]:
np.logspace(0, 3, 4)

array([   1.,   10.,  100., 1000.])

### Генерация случайных чисел

np.random.sample - случайные дробные числа от 0 до 1

In [111]:
np.random.sample(3)

array([0.20675257, 0.55565523, 0.1278292 ])

In [115]:
np.random.sample((3, 4))

array([[0.82502343, 0.33198086, 0.70606366, 0.42672973],
       [0.29411987, 0.11280781, 0.39057825, 0.25466841],
       [0.08907058, 0.16562371, 0.97476401, 0.93618431]])

Массив 48x64x3 - это может быть изображение с высотой 48, шириной 64
и значениями яркости 3 цветов для каждого пикселя (кол-во цветов)

In [117]:
np.random.sample((48, 64, 3))

array([[[0.30943358, 0.23650231, 0.42297086],
        [0.1414395 , 0.1850758 , 0.92175036],
        [0.27514151, 0.63310825, 0.45369002],
        ...,
        [0.19013061, 0.57613815, 0.6025988 ],
        [0.9837879 , 0.67375762, 0.68984506],
        [0.35401728, 0.72809301, 0.71054792]],

       [[0.03713431, 0.64770007, 0.50055584],
        [0.80007309, 0.29877004, 0.04599972],
        [0.51031062, 0.61602695, 0.22286025],
        ...,
        [0.49084995, 0.16851428, 0.72160716],
        [0.14664111, 0.76440223, 0.27998261],
        [0.22769104, 0.14190986, 0.10719685]],

       [[0.3649238 , 0.79579306, 0.17496368],
        [0.27067574, 0.59814708, 0.5728186 ],
        [0.83628361, 0.89941204, 0.06358745],
        ...,
        [0.28882052, 0.6383182 , 0.35359166],
        [0.78951818, 0.0596469 , 0.00381761],
        [0.78050463, 0.88018659, 0.17717286]],

       ...,

       [[0.55426803, 0.33635546, 0.89099476],
        [0.46457919, 0.26424874, 0.3002709 ],
        [0.84029077, 0

np.random.randn - случайные числа с нормальным распределением
(среднее значение = 0, среднеквадратичное отклонение = 1)

In [121]:
np.random.randn(2)

array([-0.45993671, -0.69325312])

In [124]:
np.random.randn(3, 2)

array([[ 0.76202117,  1.26726772],
       [-2.48236021, -0.67491365],
       [ 1.78654253, -0.71408797]])

np.random.randint - случайные целые числа

In [126]:
np.random.randint(0, 100, 10)

array([19, 54, 76, 73, 90, 38,  0, 36, 45, 27])

In [128]:
np.random.randint(1, 11, (3, 4))

array([[ 1,  4,  4,  9],
       [ 5, 10,  4, 10],
       [ 1, 10,  3,  4]])

### numpy.random.choice
позволяет выбрать случайный элемент из массива или несколько.

In [131]:
A = np.arange(11)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [136]:
np.random.choice(A)

7

In [140]:
np.random.choice(A, 3)

array([1, 7, 1])

### Изменение формы массива

In [143]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [146]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [150]:
# Когда известно кол-во строк, и не известно кол-во столбцов указываем -1 и функция сама создат массив нужного размера

np.reshape(a, (3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [153]:
# Когда неизвестно кол-во строк, но известно требуемое кол-во столбцов, также пишем -1
np.reshape(a,(-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [155]:
a.resize(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### Получение одномерного массива из многомерного

In [157]:
a = a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Соединение массивов
Для примера возьмём два массива а и b

In [162]:
a = np.zeros((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [165]:
b = np.ones((2, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [167]:
# Соединение строк вертикально
v = np.vstack((a, b))
v

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [168]:
# Соединяем строки горизонтально
w = np.hstack((a, b))
w

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [169]:
a.shape, b.shape, w.shape

((2, 3), (2, 3), (2, 6))

In [171]:
# Соединение в глубину (в третьем измерении)
r = np.dstack([a, b])
r

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])

In [172]:
r.shape

(2, 3, 2)