In [4]:
import numpy as np

In [15]:
# 1 Создаём массив и находим среднее значение по столбцам (по признакам)
a = np.array([[1, 6],
             [2, 8],
             [3, 11],
             [3, 10],
             [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [21]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

In [23]:
# 2 
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [26]:
# 3 Находим скалярное произведение столбцов
column_1 = a_centered[:,0]
column_2 = a_centered[:,1]

In [28]:
a_centered_sp = np.dot(column_1, column_2)
a_centered_sp

8.0

In [30]:
a_centered_sp / 4

2.0

In [35]:
# 4 Ковариляция
at = a.T
at

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [39]:
covar = np.cov(at)
covar

array([[1. , 2. ],
       [2. , 4.3]])

In [38]:
covar[0,1]

2.0