In [195]:
import numpy as np

In [196]:
a = [i for i in range(10)]

In [197]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [198]:
b = np.array(a)

In [199]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [200]:
b.dtype

dtype('int32')

In [201]:
type(b)

numpy.ndarray

In [202]:
b = np.array(a, dtype = float)

In [203]:
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [204]:
b = np.array(a, dtype = str)

In [205]:
b

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U1')

In [206]:
b[0]

'0'

In [207]:
b[8]

'8'

In [208]:
b.ndim

1

In [209]:
b.shape

(10,)

In [210]:
b = np.array([[0,1,2,3,4,5,6,7,8,9],
              [10,11,12,13,14,15,16,17,18,19],
              [20,21,22,23,24,25,26,27,28,29]])

In [211]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [212]:
b[1][4]

14

In [213]:
b[2, 7]

27

In [214]:
b[0:,7:]

array([[ 7,  8,  9],
       [17, 18, 19],
       [27, 28, 29]])

In [215]:
c = b[0:,:5].copy()

In [216]:
c

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [217]:
c[2,3] = 555

In [218]:
c

array([[  0,   1,   2,   3,   4],
       [ 10,  11,  12,  13,  14],
       [ 20,  21,  22, 555,  24]])

In [219]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [220]:
mas = np.array([1,2,3,4], dtype=np.int64)

In [221]:
mas.dtype

dtype('int64')

In [222]:
mas.shape

(4,)

In [223]:
b.shape

(3, 10)

In [224]:
b.ndim

2

In [225]:
b.size

30

### Скалярное произведение векторов

In [226]:
a = np.array([1,2,3,4,5],dtype ="int32")
b = np.array([6,7,8,9,10],dtype ="int32")
sp = np.dot(a,b)
sp

130

### Скалярное умножение числа на вектор

In [227]:
a.dot(-5)

array([ -5, -10, -15, -20, -25])

## Операции с векторами

 Сложение

In [228]:
a = np.array([0, 1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10, 11])

In [229]:
c = a + b

In [230]:
c

array([ 6,  8, 10, 12, 14, 16])

In [231]:
c = np.add(a, b)

In [232]:
c

array([ 6,  8, 10, 12, 14, 16])

Вычитание

In [233]:
d = np.subtract(a,b)

In [234]:
d

array([-6, -6, -6, -6, -6, -6])

Умножение вектра на скаляр (число)

In [235]:
a = np.array([0, 1, 2, 3, 4, 5])

In [236]:
a.dot(-10)

array([  0, -10, -20, -30, -40, -50])

In [237]:
np.dot(a,-10)

array([  0, -10, -20, -30, -40, -50])

Скалярное умножение векторов

In [238]:
a = np.array([0, 1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10, 11])

In [239]:
sp = a @ b

In [240]:
sp

145

In [241]:
sp = np.dot(a,b)
sp

145

# Операции с матрицами

### Сложение, вычитание

In [242]:
A = np.array([[23, 34],
             [18, 12],
             [9, 5]])

In [243]:
B = np.array([[45, 22],
             [21, 3],
             [11, 99]])

In [244]:
C = np.add(A, B)
C

array([[ 68,  56],
       [ 39,  15],
       [ 20, 104]])

In [245]:
C = np.subtract(B, A)
C

array([[ 22, -12],
       [  3,  -9],
       [  2,  94]])

### Умножение матрицы на скаляр(число)

In [246]:
X = np.array([[12, 45],
             [22,15]])
X

array([[12, 45],
       [22, 15]])

In [247]:
Y = X * 2
Y

array([[24, 90],
       [44, 30]])

In [248]:
Y = np.dot(X, 4)
Y

array([[ 48, 180],
       [ 88,  60]])

### Умножение матрицы на матрицу
Кол-во столбцов 1 матрицы должно быть равное кол-ву строк 2 матрицы

In [249]:
A = np.array([[1, 2],
             [21, 12],
             [34, 7]])

B = np.array([[22, 32, 4],
             [7, 16, 11]])

In [250]:
Z = np.dot(A, B)
Z

array([[  36,   64,   26],
       [ 546,  864,  216],
       [ 797, 1200,  213]])

### Возведение матрицы в квадрат (матрица должна быть квадратная 2x2, 3x3 и тд.)

In [251]:
A = np.array([[1, 12, 21],
             [11, 3, 5],
             [8, 6, 9]])

In [252]:
A_square = np.dot(A, A)
A_square

array([[301, 174, 270],
       [ 84, 171, 291],
       [146, 168, 279]])

In [253]:
A_square = np.linalg.matrix_power(A, 2)
A_square

array([[301, 174, 270],
       [ 84, 171, 291],
       [146, 168, 279]])

### Создание и использование единичной матрицы.
Квадратная матрица с 1 на главной диагонали и остальными нулями. При умножении подходящей по размеру матрицы на единичную
матрица не меняется.

In [254]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [255]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])

In [256]:
np.dot(A, I)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [257]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [258]:
np.dot(I, A)

array([[1., 2., 3.],
       [4., 5., 6.]])

### Транспонирование матрицы

In [259]:
A = np.array([[1, 12],
             [11, 3],
             [8, 6]])

In [260]:
At = A.transpose()
At

array([[ 1, 11,  8],
       [12,  3,  6]])

In [261]:
At = A.T
At

array([[ 1, 11,  8],
       [12,  3,  6]])

Пример применения транспонирования матрицы (после транспонирования матрицы умножение возможно)

In [262]:
X = np.array([[1, 2],
             [3, 4],
             [5, 6]])

Y = np.array([[3, 4],
             [5, 6],
             [7, 8],
             [2, 9]])

In [263]:
Yt = Y.T
Yt

array([[3, 5, 7, 2],
       [4, 6, 8, 9]])

In [264]:
np.dot(X, Yt)

array([[11, 17, 23, 20],
       [25, 39, 53, 42],
       [39, 61, 83, 64]])

 ### Вычисление определителя и ранга матрицы 
    (Определитель можно найти только у квадратных матриц, ранг у всех)

In [265]:
A = np.array([[0, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

In [266]:
np.linalg.det(A)

2.9999999999999982

In [267]:
np.linalg.matrix_rank(A)

3

In [268]:
B = np.array([[0, 2, 3],
             [4, 5, 6]])

In [269]:
np.linalg.matrix_rank(B)

2

### Вычисление обратной матрицы

In [270]:
C = np.array([[1, 2, 3],
             [5, 6, 8],
             [2, 12, 21]])

In [271]:
C_inv = np.linalg.inv(C)
C_inv

array([[ -7.5 ,   1.5 ,   0.5 ],
       [ 22.25,  -3.75,  -1.75],
       [-12.  ,   2.  ,   1.  ]])

In [272]:
C_inv_2 = np.linalg.inv(C_inv)
C_inv_2

array([[ 1.,  2.,  3.],
       [ 5.,  6.,  8.],
       [ 2., 12., 21.]])

# Генерирование массивов

Генерация массива с нулями

In [273]:
A = np.zeros((3, 4))
A

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Генерация массива с единицами

In [274]:
B = np.ones((2,5))
B

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Генерация массива последовательности

In [275]:
C = np.arange(10)
C

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [276]:
C = np.arange(10, 0, -1)
C

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

linspace- правая граница будет включена, вместо шага указываем кол-во элементов.

In [277]:
np.linspace(0, 9.9, 100)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

Logspace - не сами числа, а степени числа 10

In [278]:
np.logspace(0, 3, 4)

array([   1.,   10.,  100., 1000.])

### Генерация случайных чисел

np.random.sample - случайные дробные числа от 0 до 1

In [279]:
np.random.sample(3)

array([0.09368843, 0.16437082, 0.67783632])

In [280]:
np.random.sample((3, 4))

array([[0.16888175, 0.39660751, 0.260547  , 0.73677543],
       [0.97225049, 0.26372101, 0.94038209, 0.88851023],
       [0.37573985, 0.89894417, 0.01794337, 0.59969167]])

Массив 48x64x3 - это может быть изображение с высотой 48, шириной 64
и значениями яркости 3 цветов для каждого пикселя (кол-во цветов)

In [281]:
np.random.sample((48, 64, 3))

array([[[4.08456591e-01, 7.98731621e-01, 2.28382956e-01],
        [1.53613492e-01, 7.21318228e-01, 4.06566609e-02],
        [3.28364474e-01, 8.08473155e-02, 8.63402301e-01],
        ...,
        [6.18666827e-01, 2.58085161e-01, 1.99514692e-01],
        [4.45591938e-02, 1.48047095e-01, 1.67735789e-01],
        [4.06118820e-01, 6.83688240e-01, 3.01356526e-01]],

       [[8.89335231e-01, 6.98834937e-01, 4.66607089e-02],
        [1.34309979e-02, 6.20724578e-01, 2.12160146e-01],
        [4.34100736e-01, 6.39901851e-02, 9.95082242e-01],
        ...,
        [9.81460511e-01, 1.59187758e-02, 5.88251421e-01],
        [7.86640753e-01, 8.33882290e-01, 7.95605854e-01],
        [7.13618591e-01, 5.17340214e-02, 5.69823231e-02]],

       [[5.79703241e-01, 4.67342947e-01, 8.08735500e-01],
        [2.23735571e-02, 4.60028381e-01, 6.27740092e-01],
        [6.41203649e-01, 5.32556375e-01, 6.36109264e-01],
        ...,
        [2.74469091e-01, 6.28720228e-01, 1.12618402e-01],
        [3.40257679e-01, 6.16

np.random.randn - случайные числа с нормальным распределением
(среднее значение = 0, среднеквадратичное отклонение = 1)

In [282]:
np.random.randn(2)

array([ 0.87790611, -0.14989397])

In [283]:
np.random.randn(3, 2)

array([[-0.12052045,  1.30111074],
       [ 0.19711467,  1.21746103],
       [ 1.10769575, -0.70148267]])

np.random.randint - случайные целые числа

In [284]:
np.random.randint(0, 100, 10)

array([72, 60,  8, 85, 51, 85, 31, 89, 86, 40])

In [285]:
np.random.randint(1, 11, (3, 4))

array([[ 4,  5, 10,  8],
       [ 4,  2,  5, 10],
       [ 9,  6,  4,  4]])

### numpy.random.choice
позволяет выбрать случайный элемент из массива или несколько.

In [286]:
A = np.arange(11)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [287]:
np.random.choice(A)

1

In [288]:
np.random.choice(A, 3)

array([7, 4, 1])

### Изменение формы массива

In [289]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [290]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [291]:
# Когда известно кол-во строк, и не известно кол-во столбцов указываем -1 и функция сама создат массив нужного размера

np.reshape(a, (3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [292]:
# Когда неизвестно кол-во строк, но известно требуемое кол-во столбцов, также пишем -1
np.reshape(a,(-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [293]:
a.resize(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### Получение одномерного массива из многомерного

In [294]:
a = a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Соединение массивов
Для примера возьмём два массива а и b

In [295]:
a = np.zeros((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [296]:
b = np.ones((2, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [297]:
# Соединение строк вертикально
v = np.vstack((a, b))
v

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [298]:
# Соединяем строки горизонтально
w = np.hstack((a, b))
w

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [299]:
a.shape, b.shape, w.shape

((2, 3), (2, 3), (2, 6))

In [300]:
# Соединение в глубину (в третьем измерении)
r = np.dstack([a, b])
r

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])

In [301]:
r.shape

(2, 3, 2)

## Выбор данных 

In [302]:
a = np.random.randint(0, 20, 10)
a

array([15,  8,  5, 18, 11,  8, 16, 13, 11,  6])

In [303]:
a[a>10]

array([15, 18, 11, 16, 13, 11])

In [304]:
# Логическое "и" - &
a[(a > 10) & (a % 2 == 0)]

array([18, 16])

In [305]:
# Логическое или "|"
a[(a > 10) | (a % 3 == 0)]

array([15, 18, 11, 16, 13, 11,  6])

#### numpy.where
Возвращает индексы элементов, удовлетворяющих условию

In [306]:
a

array([15,  8,  5, 18, 11,  8, 16, 13, 11,  6])

In [307]:
np.where(a>10)

(array([0, 3, 4, 6, 7, 8], dtype=int64),)

#### Вариан применения сложнее
Если в условии True, то берем элемент из 1-го массива, если False, то из 2-го 
(В функции 3 аргумента, первый - маска)

In [308]:
a = [1, 2, 3]
b = [4, 6, 8]

In [309]:
np.where([True, False, True], a, b)

array([1, 6, 3])

### Сортировка

In [310]:
a = np.array([[2, 2, 3, 4],
             [1, 5, 7, 8],
             [12, 21, 9, 6]])

In [311]:
# Указываем порядок строк для всех столбцов по первому
a[[1, 0, 2], :]

array([[ 1,  5,  7,  8],
       [ 2,  2,  3,  4],
       [12, 21,  9,  6]])

In [312]:
# Метод возвращает индексы массива сортировки строк по первому столбцу
a[:,0].argsort()

array([1, 0, 2], dtype=int64)

In [313]:
# (через срез) Указываем порядок вывода строк для всех столбцов, 
# через метод argsort(сортировка для всех строк по 1-ому столбцу)
a[a[:,0].argsort(),:]

array([[ 1,  5,  7,  8],
       [ 2,  2,  3,  4],
       [12, 21,  9,  6]])

### Случайное перемешивание массивов

In [314]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [315]:
np.random.shuffle(a)
a

array([9, 1, 6, 4, 0, 5, 8, 2, 7, 3])

Двумерные массивы

In [316]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [317]:
# В двухмерных массивах перемешиваются только строки
np.random.shuffle(b)
b

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

### Математические функции ко всему массиву

In [318]:
a = np.arange(1,7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [319]:
# Находим Логарифм по основанию е
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [320]:
# Экспонента
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [321]:
a.sum()

21

In [322]:
# Сумма по столбцам
a.sum(axis = 0)

array([5, 7, 9])

In [323]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [324]:
a + 10

array([[11, 12, 13],
       [14, 15, 16]])

In [325]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [326]:
b = np.arange(13, 25).reshape(3, 4)
b

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [327]:
a * b

array([[  0,  14,  30,  48],
       [ 68,  90, 114, 140],
       [168, 198, 230, 264]])

### Broadcasting (на примере сложения)

In [328]:
a = np.array([[1, 2],
             [3, 4],
             [5, 6]])

b = np.array([1, 2])


In [329]:
# В данном примере не совпадает количество строк, поэтому матрица b будет прибавляться к каждой строке матрицы a
a + b

array([[2, 4],
       [4, 6],
       [6, 8]])

In [330]:
c = np.array([[1],
             [2],
             [3]])

In [331]:
# Здесь матрица с будет прибавляться к каждому столбцу матрицы а
c + a

array([[2, 3],
       [5, 6],
       [8, 9]])

### Статистические функции

In [332]:
a = np.random.randint(1, 12,(3, 4))
a

array([[ 4,  5, 10,  5],
       [ 6,  5,  4,  1],
       [ 7, 10,  8, 11]])

In [333]:
# минимум для матрицы
a.min()

1

In [334]:
a.max()

11

In [335]:
# Минимум для каждого столбца
a.min(axis = 0)

array([4, 5, 4, 1])

In [336]:
# Максимум для каждой строки
a.max(axis = 1)

array([10,  6, 11])

In [337]:
# Среднее значение для каждого столбца
a.mean(axis = 0)

array([5.66666667, 6.66666667, 7.33333333, 5.66666667])

In [338]:
# Среднеквадратичное отклонение
a.std(axis = 0)

array([1.24721913, 2.3570226 , 2.49443826, 4.10960934])

### Запись и чтение массива из файла

In [339]:
# Запись массива в файл и сохранение
np.save('a.npy', a)

In [340]:
# Чтение массива из файла
b = np.load('a.npy')

In [341]:
b

array([[ 4,  5, 10,  5],
       [ 6,  5,  4,  1],
       [ 7, 10,  8, 11]])